<header class="flex-shrink-0">  
    <nav class="navbar navbar-expand-md navbar-dark bg-dark px-3">
        <a class="navbar-brand" href="/">Анализатор страниц</a>
        <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link <?= (isset($activeMenu) && $activeMenu === 'main') ? 'active' : '';?>" href="<?= $router->urlFor('mainpage.index') ?>">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link <?= (isset($activeMenu) && $activeMenu === 'urls') ? 'active' : '';?>" href="<?= $router->urlFor('urls.store') ?>">Сайты</a>
                </li>
            </ul>
        </div>
    </nav>
    
    <?php if (isset($flash)) : ?>
        <?php foreach ($flash as $messageType => $messages) : ?>
            <?php foreach ($messages as $message) : ?>
                <div class="alert alert-<?= $messageType ?>" role="alert"><?= $message ?></div>
            <?php endforeach ?>
        <?php endforeach ?>
    <?php endif ?>
</header>